### PR TITLE
Enhanced compatibility with neo4j 3.x

### PR DESCRIPTION
**Pull request by ogmueller**
Hello,

i've update your temp branch to be fully compatible with neo4j 3.x and added some minor "features". There is more information in the commit messages.
maybe you can create a 1.1 with it. all tests are working on my side.

regards,
oliver

### CODE REVIEW

**Comment by ogmueller** [comment]
Do not merge right now. There is still a problem with allow external connections. Will fix it now.

**Comment by ogmueller** [comment]
Fixed and pushed. You may merge it now, if you like the changes.

**Comment by carlosforero** [comment]
Hi @ogmueller, I had this project outdated, because my time has been committed to other projects that are not using Neo4j. But has always been in my plans to continue with this tool. Now your contribution looks great, and that is a good reason to come back here with frequent updates!. Thank you so much!

I'm going to run the tests right now, then push if everything is fine.

**Comment by carlosforero** [comment]
@ogmueller test `CreateAnInstanceCorrectlyWithDifferentVariationsOfParameters` is failing on my side. I'm not so clear about the reason. I will check it tonight.

**Comment by ogmueller** [comment]
Maybe it fails with neo4j v1.9? I don't have Java <1.8 installed and excluded neo4j v1.9 automatically due to incompatibility issues with this Java versions.

```
# ./test.sh -V CreateAnInstanceCorrectlyWithDifferentVariationsOfParameters

Starting test CreateAnInstanceCorrectlyWithDifferentVariationsOfParameters twitter
........
Starting test CreateAnInstanceCorrectlyWithDifferentVariationsOfParameters -p8484 twitter
........
Starting test CreateAnInstanceCorrectlyWithDifferentVariationsOfParameters -s9495 twitter
........
Starting test CreateAnInstanceCorrectlyWithDifferentVariationsOfParameters -b9496 twitter
........
Starting test CreateAnInstanceCorrectlyWithDifferentVariationsOfParameters -p9494 -s8484 twitter
........
Starting test CreateAnInstanceCorrectlyWithDifferentVariationsOfParameters -s8484 -b9496 twitter
........
Starting test CreateAnInstanceCorrectlyWithDifferentVariationsOfParameters -p8484 -s9495 -b9499 twitter
........
Starting test CreateAnInstanceCorrectlyWithDifferentVariationsOfParameters -v3.3.1 twitter
........
Starting test CreateAnInstanceCorrectlyWithDifferentVariationsOfParameters -v3.3.1 -e enterprise twitter
........
Starting test CreateAnInstanceCorrectlyWithDifferentVariationsOfParameters -v3.3.1 -e community twitter
........
Starting test CreateAnInstanceCorrectlyWithDifferentVariationsOfParameters -p8484 -v3.3.1 twitter
........
Starting test CreateAnInstanceCorrectlyWithDifferentVariationsOfParameters -s9495 -v3.3.1 twitter
........
Starting test CreateAnInstanceCorrectlyWithDifferentVariationsOfParameters -b9496 -v3.3.1 twitter
........
Starting test CreateAnInstanceCorrectlyWithDifferentVariationsOfParameters -p9494 -s8484 -v3.3.1 twitter
........
Starting test CreateAnInstanceCorrectlyWithDifferentVariationsOfParameters -p8484 -b9496 -v3.3.1 twitter
........
Starting test CreateAnInstanceCorrectlyWithDifferentVariationsOfParameters -s8484 -b9496 -v3.3.1 twitter
........
Starting test CreateAnInstanceCorrectlyWithDifferentVariationsOfParameters -p8484 -s9494 -b9496 -v3.3.1 twitter
........
Starting test CreateAnInstanceCorrectlyWithDifferentVariationsOfParameters -v2.3.6 twitter
.......
Starting test CreateAnInstanceCorrectlyWithDifferentVariationsOfParameters -v2.3.6 -e enterprise twitter
.......
Starting test CreateAnInstanceCorrectlyWithDifferentVariationsOfParameters -v2.3.6 -e community twitter
.......
Starting test CreateAnInstanceCorrectlyWithDifferentVariationsOfParameters -p8484 -v2.3.6 twitter
.......
Starting test CreateAnInstanceCorrectlyWithDifferentVariationsOfParameters -s9495 -v2.3.6 twitter
.......
Starting test CreateAnInstanceCorrectlyWithDifferentVariationsOfParameters -p9494 -s8484 -v2.3.6 twitter
.......
all 178 CreateAnInstanceCorrectlyWithDifferentVariationsOfParameters tests passed in 18.775s.
```

**Comment by ogmueller** [comment]
Have you ever heard of Google's [codestyle for shell](https://google.github.io/styleguide/shell.xml). It is short, but well written and most of it makes sense and helps. Would you mind if I change some of the code to match it? I mean whenever touching a piece of code as a refactoring?

**Comment by carlosforero** [comment]
Sorry for my delay.

The problem with the test is only in Mac OSx. As far as I see, I've added `.bak` with the `sed` command, to get compatibility with OSx such as is explained in this SO: https://stackoverflow.com/questions/4247068

This is in `set_port`, `set_https_port` and `set_bolt_port`.

I suppose the same behavior is in Unix FreeBSD, in case you don't have a Mac and you want to test.

So, let me know either you can fix it in your pull request, or if you have another idea about it.

**Comment by carlosforero** [comment]
@ogmueller about [codestyle for shell](https://google.github.io/styleguide/shell.xml), I think is an excellent idea. Then we can add it to the guidelines for developers.

**Comment by ogmueller** [comment]
i tested it on my mac and it is working without extension nowadays. maybe they changed it in the newer OSes. the man page says:

     -i extension
             Edit files in-place, saving backups with the specified extension.  If a zero-length extension is given, no backup
             will be saved.  It is not recommended to give a zero-length extension when in-place editing files, as you risk
             corruption or partial content in situations where disk space is exhausted, etc.

can you retest it? i have high sierra installed and sed is working in it without extension.

**Comment by carlosforero** [comment]
My tests on mac and linux, are reporting some problems yet. I resolved some issues, but I need to see more. I will try to commit my fixes before christmas. For now I'm going to merge this pull request.

Merry christmas!

**Pull request merged**
